### ISSUE TITLE
Empty Sync Report

### ISSUE THREAD

**Issue by tombeech** [lwhitelock/HuduM365Automation#1]
Hello,

Is there a log somewhere I can see whats going on. I've mapped a few companies in hudu to O365 using the provided script to test, before doing everyone. I've deployed to Azure and checked the secure access is all good. 

M365 to Hudu Sync Report - 2022-01-20 13:14:54
Total Customers
0
Total Users
0
Total Devices
0
Total Errors
0
Customers with Errors
0

I'm just looking for a bit of advice on how to start debugging please.

Thanks a lot!

Tom

**Comment by jlsiemering** [comment]
Same behavior here. Logs aren't showing any errors, but not much information I know what to do with either :)

**Comment by lwhitelock** [comment]
This error most often happens when there is an issue with your tokens. Give yourself permissions to the key vault, and check you didn't accidentally leave the placeholder text at the start or end of any of the tokens.
