### ISSUE TITLE
Refresh Token Expired

### ISSUE THREAD

**Issue by CorneliousJD** [lwhitelock/HuduM365Automation#21]
This hasn't been running for me since 7/2022 I guess. I'm troubleshooting now as it ketp showing 0 customers, 0 users, etc, so I set it up to run in package mode now however after doing that it's showing the following.

The refresh token has expired due to inactivity. The token was issued on 2022-04-11T19:23:48.0570802Z and was inactive for 90.00:00:00

How can I generate a new refresh token for this?

**Comment by JohnDuprey** [comment]
Do you have a Conditional Access policy that limits the token lifetime to 90 days? Or the "Allow users to remember devices for X days" in the Per-User MFA service settings?

https://cipp.app/docs/general/troubleshooting/#multi-factor-authentication-troubleshooting

**Comment by CorneliousJD** [comment]
> Do you have a Conditional Access policy that limits the token lifetime to 90 days? Or the "Allow users to remember devices for X days" in the Per-User MFA service settings?
> 
> https://cipp.app/docs/general/troubleshooting/#multi-factor-authentication-troubleshooting

I do not - also for what it's worth our CIPP tokens are working just fine and have been for quite some time. 
I spent a few hours troubleshooting last night and ended up refreshing tokens and then it started erroring with a malformed request so I blew away the resource group and just redeployed the function app from scratch and wanted to test with a manual run, but the "functions" in the function app are now blank.

![image](https://user-images.githubusercontent.com/724777/227526517-748d5df0-e352-4237-b748-2fb72051fbdf.png)

**Comment by CorneliousJD** [comment]
I needed to deploy it via my own github fork - after that it's working fine now again. not sure what caused it to originally stop but the redeployment seems to have done the trick with running as a package from my own fork.

it's updating now
