### ISSUE TITLE
cant refresh exchangetoken

### ISSUE THREAD

**Issue by kikkn** [lwhitelock/HuduM365Automation#25]
Exchange token wont refresh since exchange application is deprecated: https://techcommunity.microsoft.com/t5/exchange-team-blog/mfa-app-id-deprecation-in-exchange-online/ba-p/4036067

Would be really happy if it was possible to fix :)
Or what info are we missing if we cut out the exchangetoken?

**Comment by JohnDuprey** [comment]
No data is missing, everything can be obtained using the Graph Token now
https://github.com/lwhitelock/HuduM365Automation/commit/cf1ac37e9d26653835c6e07e46e090940c40fdee
