### ISSUE TITLE
Users are created although disabled

### ISSUE THREAD

**Issue by Tan-DE** [lwhitelock/HuduM365Automation#3]
```
Wrong: $CreateUsers = [bool]$env:CreateUsers
Correct: $CreateUsers = [System.Convert]::ToBoolean($env:CreateUsers)

Internal Test:
$test ="false"
$res1 = [bool]$test
$test1 << $true
```

The same applies to all Boolean parameters:
$CreateDevices = [bool]$env:CreateDevices
$CreateMobileDevices = [bool]$env:CreateMobileDevices
$CreateInOverview = [bool] $env:CreateInOverview
etc.

**Comment by lwhitelock** [comment]
Whoops I was sure I tested that worked! Thanks for the heads up!
